# Generated by Django 3.2.4 on 2021-06-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('homepage', models.URLField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=24, null=True)),
                ('adult', models.BooleanField()),
                ('budget', models.IntegerField(null=True)),
                ('genres', models.JSONField(null=True)),
            ],
        ),
    ]
