# Generated by Django 3.2.4 on 2021-06-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210622_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='homepage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
