# Generated by Django 3.2.4 on 2021-06-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id']},
        ),
    ]
